[tag]
prefix = "tag"
body = "*$0*"

[modeline]
prefix = "modeline"
body = "vim:tw=78:ts=8:noet:ft=help:norl:"
if = "vimscript"
eval = "line('.') == line('$')"

[new_section]
prefix = "new_section"
body = """
==============================================================================
$0

"""
