[for]
prefix = "for"
body = """
foo ${1:var} in ${2:list}
	$0
endfor\
"""

["local function"]
prefix = "lfn"
body = """
function s:$1($2) abort
	$0
endfunction\
"""

[rt]
prefix = "rt"
body = "return"
