[rt]
prefix = "rt"
body = "return"

[l]
prefix = "l"
body = "let $1 = $0"

[c]
prefix = "c"
body = "const $1 = $0"

["local function"]
prefix = "lfn"
body = """
function s:$1($2) abort
	$0
endfunction\
"""

[for]
prefix = "for"
body = """
for ${1:var} in ${2:list}
	$0
endfor\
"""

[if]
prefix = "if"
body = """
if $1
	$0
endif\
"""

[aug]
prefix = "aug"
body = """
augroup $1
	au!
	$0
augroup END\
"""
