-- local ls = require("luasnip")
-- local s = ls.snippet
-- local sn = ls.snippet_node
-- local isn = ls.indent_snippet_node
-- local t = ls.text_node
-- local i = ls.insert_node
-- local f = ls.function_node
-- local c = ls.choice_node
-- local d = ls.dynamic_node
-- local r = ls.restore_node
--
-- local function copy(args)
--     return args[1][1]
-- end
--
-- ls.snippets = {
--     lua = {
--         s("inc", {
--             i(1),
--             t(" = "),
--             f(copy, 1),
--             t(" + 1"),
--         }),
--         s("dec", {
--             i(1),
--             t(" = "),
--             f(copy, 1),
--             t(" - 1"),
--         }),
--     },
-- }
