---
version: 2
root-markers:
  - .git/

tools:
  fixjson: &fixjson
    format-command: 'fixjson'
    format-stdin: true

  jsonlint: &jsonlint
    lint-command: 'jsonlint -c'
    lint-stdin: true
    lint-formats:
      - 'line %l, col %c, found: %m'

  stylua: &stylua
    format-command: 'stylua --config-path ~/.config/stylua.toml -'
    format-stdin: true

  python-black: &python-black
    format-command: 'black -q -'
    format-stdin: true

  shfmt: &shfmt
    format-command: 'shfmt -ci -s -bn -i 2'
    format-stdin: true

languages:
  json:
    - <<: *fixjson
    - <<: *jsonlint

  lua:
    - <<: *stylua

  python:
    - <<: *python-black

  sh:
    - <<: *shfmt
