[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_source = '''
    require("mason").setup()
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['mason.nvim', 'nvim-lspconfig', 'fidget.nvim', 'nvim-cmp']
on_event = 'BufRead'
lua_source = '''
    require("rc.plugins.mason-lspconfig")
'''

[[plugins]]
repo = 'glepnir/lspsaga.nvim'
rev = 'main'
lua_source = '''
    require("lspsaga").init_lsp_saga({
      diagnostic_header = { " ", " ", " ", " " },
      code_action_lightbulb = {
        enable = true,
        enable_in_insert = false,
        sign = false,
        virtual_text = true,
      },
    })
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
lua_source = '''
    require("fidget").setup({})
'''

[[plugins]]
repo = 'hrsh7th/nvim-gtd'
on_event = ['BufRead']
lua_add = '''
    vim.keymap.set("n", "gd", function()
      require("gtd").exec({ command = "edit" })
    end)
    -- vim.keymap.set("n", "gfs", function()
    --   require("gtd").exec({ command = "split" })
    -- end)
    -- vim.keymap.set("n", "gfv", function()
    --   require("gtd").exec({ command = "vsplit" })
    -- end)
'''
lua_source = '''
    require("gtd").setup({
      sources = {
        { name = "lsp" },
        { name = "findup" },
        { name = "walk" },
      },
      on_locations = function(params, locations)
        local paths, path2loc = {}, {}
        for _, v in ipairs(locations) do
          local path = vim.uri_to_fname(v.targetUri)
          table.insert(paths, path)
          path2loc[path] = v
        end
        require("fzf-lua").fzf_exec(paths, {
          previewer = "builtin",
          prompt = "Select file> ",
          fn_selected = function(path, o)
            path = path[1]
            if path then
              vim.pretty_print(path, path2loc)
              local location = path2loc[path]
              vim.pretty_print(location)
              require("gtd")._open(params, location)
            else
              print("Canceled")
            end
          end
        })
      end
    })
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
on_ft = ['lua', 'python', 'json']
lua_source = '''
    local null = require("null-ls")
    local b = null.builtins

    null.setup({
      diagnostics_format = "#{m} (#{s}: #{c})",
      sources = {
        function()
          local utils = require("null-ls.utils").make_conditional_utils()
          if utils.root_has_file("stylua.toml") then
            return b.formatting.stylua
          elseif utils.root_has_file(".stylua.toml") then
            return b.formatting.stylua.with({
              extra_args = { "--config-path", "./.stylua.toml" },
            })
          else
            return b.formatting.stylua.with({
              extra_args = { "--config-path", vim.fn.expand("~/.config/stylua.toml") },
            })
          end
        end,
        b.formatting.fixjson,
        b.formatting.black,
      },
    })
'''
