[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_source = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lua_source = '''
    require("rc.plugins.lualine")
'''
