[[plugins]]
repo = 'lewis6991/impatient.nvim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_source = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'feline-nvim/feline.nvim'
depends = 'nvim-web-devicons'
lua_source = '''
    require("rc.plugins.feline")
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_source = '''
    call operator#sandwich#set('add', 'char', 'skip_space', 1)
'''
