[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = 'vim-vsnip'
on_event = ['InsertEnter', 'CmdlineEnter']
lua_source = '''
    require("rc.plugins.nvim-cmp")
'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lua'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = '~/plugin/cmp-dictionary'
on_source = 'nvim-cmp'
lua_source = '''
    local dict = require("cmp_dictionary")

    dict.setup({
      exact = 2,
      async = true,
      first_case_insensitive = true,
      document = true,
    })

    dict.switcher({
      filetype = {
        autohotkey = "~/dotfiles/dict/ahk.dict",
      },
      spelllang = {
        en = "~/.dict/en.dict",
      },
    })
'''

[[plugins]]
repo = '~/plugin/cmp-skkeleton'
on_source = 'nvim-cmp'
