[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
if = 0
hook_source = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_source = '''
    colorscheme nightfox
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
if = 0
hook_source = '''
    colorscheme tokyonight
'''

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 0
