[[plugins]]
repo = 'Shougo/ddu.vim'
lua_add = '''
    local height, row = (function()
      local lines = vim.opt.lines:get()
      return math.floor(lines * 0.8), math.floor(lines * 0.1)
    end)()
    local width, col = (function()
      local columns = vim.opt.columns:get()
      return math.floor(columns * 0.8), math.floor(columns * 0.1)
    end)()

    vim.fn["ddu#custom#patch_global"]({
      ui = "ff",
      uiParams = {
        ff = {
          startFilter = true,
          prompt = "> ",
          split = "floating",
          winHeight = height,
          winRow = row,
          winWidth = width,
          winCol = col,
          floatingBorder = "single",
          filterFloatingPosition = "top",
          autoAction = {
            name = "preview",
          },
          previewFloating = true,
          previewFloatingBorder = "single",
          previewSplit = "vertical",
          previewFloatingTitle = "Preview",
          previewWidth = math.floor(width / 2),
          highlights = {
            floating = "Normal",
            floatingBorder = "Normal",
          },
        },
      },
      sourceOptions = {
        _ = {
          ignoreCase = true,
          matchers = { "matcher_fzf" },
          sorters = {},
        },
      },
    })
    vim.api.nvim_create_user_command("Ddu", function(args)
      local sub_command = args.args
      local f = require("ddu_command")[sub_command]
      if f then
        f()
      else
        vim.notify("Unknown sub command: " .. sub_command)
      end
    end, {
      nargs = 1,
      complete = function()
        return vim.tbl_keys(require("ddu_command"))
      end,
    })
'''

# UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'

# Sources
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
lua_add = '''
    require("rc.utils").package_set("ddu_command", "files", function()
      require("rc.ddu").start({
        "file_rec",
      })
    end)
'''

[[plugins]]
repo = 'shun/ddu-source-rg'
lua_add = '''
    require("rc.utils").package_set("ddu_command", "live_grep", function()
      local root = require("rc.utils").find_root()
      require("rc.ddu").start({
        "rg",
        name = "file#rg",
        sourceOptions = {
          rg = {
            path = root,
            volatile = true,
          },
        },
        uiParams = {
          ff = {
            ignoreEmpty = false,
            autoResize = false,
          },
        },
      })
    end)
'''

# Filters
[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

# Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
