# Prerequisite plugins {{{
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
    let g:context_filetype#search_offset = 500
'''

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'
# }}}

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
hook_add = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'itchyny/vim-qfedit'

[[plugins]]
repo = "uga-rosa/ugaterm.nvim"
lua_add = '''
    vim.keymap.set({ "n", "t" }, "<C-t>", "<Cmd>UgatermToggle<CR>")
    vim.keymap.set({ "n", "t" }, "<M-n>", "<Cmd>UgatermNewWithName<CR>")
    vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
'''

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = '''
    nnoremap <Space>c <Plug>OSCYankOperator
    nnoremap <Space>cc <Plug>OSCYankOperator_
    xnoremap <Space>c <Plug>OSCYankVisual
'''
