[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
hook_source = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
    let g:context_filetype#search_offset = 500
'''

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'itchyny/vim-qfedit'

[[plugins]]
repo = 'delphinus/cellwidths.nvim'
lua_source = '''
    require("cellwidths").setup({
      name = "default",
    })
'''

[[plugins]]
repo = 'rebelot/heirline.nvim'
depends = 'nvim-navic'
lua_source = '''
    require("rc.heirline")
'''
