[ftplugin]

_ = '''
    setl formatoptions-=t
    setl formatoptions-=c
    setl formatoptions-=r
    setl formatoptions-=o
    setl formatoptions+=mMl
'''

lua = '''
    let stylua_toml = filereadable('stylua.toml') ? 'stylua.toml' 
            \ : filereadable('.stylua.toml') ? '.stylua.toml' : '~/.config/stylua.toml'
    let [tab_size, is_hard_tab] = [2, 0]
    for line in readfile(expand(stylua_toml))
      if line =~# 'indent_width'
        let tab_size = str2nr(matchstr(line, '\d\+'))
      elseif line =~# 'indent_type'
        let is_hard_tab = line =~# 'Tabs'
      endif
    endfor
    lua require("rc").set_indent(tab_size, is_hard_tab)
'''

typescript_vim_sh_html_xhtml_nim_markdown = '''
    lua require("rc").set_indent(2)
'''

python = '''
    lua require("rc").set_indent(4)
'''

qf_go = '''
    lua require("rc").set_indent(4, true)
'''

help = '''
    lua require("rc").set_indent(8, true)
'''

toml = '''
    lua require("rc").set_indent(4)

    setl foldenable
    setl foldmethod=expr
    setl foldexpr=<SID>fold_expr(v:lnum)

    function! s:fold_expr(lnum) abort
      let line = getline(a:lnum)
      return line ==# '' || line[0:3] ==# '    '
    endfunction
'''
