# Prerequisite plugins {{{
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
    let g:context_filetype#search_offset = 500
'''

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'
# }}}

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
hook_add = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'itchyny/vim-qfedit'

[[plugins]]
repo = 'delphinus/cellwidths.nvim'
lua_source = '''
    require("cellwidths").setup({
      name = "default",
    })
'''

[[plugins]]
repo = 'rebelot/heirline.nvim'
depends = 'nvim-navic'
lua_source = '''
    require("rc.heirline")
'''

[[plugins]]
repo = "uga-rosa/ugaterm.nvim"
lua_add = '''
    vim.keymap.set({ "n", "t" }, "<C-t>", "<Cmd>UgatermToggle<CR>")
    vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
lua_add = '''
    vim.keymap.set({ "i", "c" }, "<C-j>", "<Plug>(skkeleton-toggle)")
'''
lua_source = '''
    vim.g["skkeleton#mapped_keys"] = { "<c-l>" }
    vim.fn["skkeleton#register_keymap"]("input", "<c-q>", "katakana")
    vim.fn["skkeleton#register_keymap"]("input", "<c-l>", "zenkaku")
    vim.fn["skkeleton#register_keymap"]("input", "'", "henkanPoint")
    local path = vim.fn.stdpath("config") .. "/script/azik.json"
    local buffer = vim.fs.read(path)
    local kanaTable = vim.json.decode(buffer)
    kanaTable[" "] = "henkanFirst"
    kanaTable["/"] = "abbrev"
    vim.fn["skkeleton#register_kanatable"]("azik", kanaTable, true)

    vim.fn["skkeleton#config"]({
      kanaTable = "azik",
      eggLikeNewline = true,
      globalDictionaries = {
        "~/.skk/SKK-JISYO.L",
        "~/.skk/SKK-JISYO.edict2",
      },
      markerHenkan = "<>",
      markerHenkanSelect = ">>",
      registerConvertResult = true,
    })
'''
