# Prerequisite plugins {{{
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kkharji/sqlite.lua'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
    let g:context_filetype#search_offset = 500
'''

[[plugins]]
repo = 'thinca/vim-themis'
path = '~/.local/share/vim-themis'

[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
# }}}

[[plugins]]
repo = 'bluz71/vim-nightfly-colors'
hook_add = '''
    let g:nightflyItalics = v:false
    colorscheme nightfly
'''

[[plugins]]
repo = 'itchyny/vim-qfedit'

[[plugins]]
repo = "uga-rosa/ugaterm.nvim"
lua_add = '''
    vim.keymap.set({ "n", "t" }, "<C-t>", "<Cmd>UgatermToggle<CR>")
    vim.keymap.set({ "n", "t" }, "<M-n>", "<Cmd>UgatermNewWithName<CR>")
    vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
'''

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = '''
    nnoremap <Space>c <Plug>OSCYankOperator
    nnoremap <Space>cc <Plug>OSCYankOperator_
    xnoremap <Space>c <Plug>OSCYankVisual
'''

[[plugins]]
repo = 'skk-dev/dict'
if = 0
path = '~/.local/share/skk'

[[plugins]]
repo = 'vim-skk/skkeleton'
lua_add = '''
    vim.keymap.set({ "i", "c" }, "<C-j>", "<Plug>(skkeleton-toggle)")

    vim.api.nvim_create_autocmd("User", {
      pattern = "DenopsPluginPost:skkeleton",
      callback = function()
        vim.g["skkeleton#mapped_keys"] = { "<c-l>" }
        vim.fn["skkeleton#register_keymap"]("input", "<c-q>", "katakana")
        vim.fn["skkeleton#register_keymap"]("input", "<c-l>", "zenkaku")
        vim.fn["skkeleton#register_keymap"]("input", "'", "henkanPoint")
        local path = vim.fn.stdpath("config") .. "/script/azik_skkeleton.json"
        local buffer = vim.fs.read(path)
        local kanaTable = vim.json.decode(buffer)
        kanaTable[" "] = "henkanFirst"
        kanaTable["/"] = "abbrev"
        vim.fn["skkeleton#register_kanatable"]("azik", kanaTable, true)

        local dict_dir = vim.fn["dein#get"]("dict").path
        vim.fn["skkeleton#config"]({
          kanaTable = "azik",
          eggLikeNewline = true,
          globalDictionaries = {
            vim.fs.joinpath(dict_dir, "SKK-JISYO.L"),
          },
          userJisyo = "~/.secret/SKK-JISYO.user",
          markerHenkan = "<>",
          markerHenkanSelect = ">>",
          registerConvertResult = true,
        })
      end,
    })
'''

[[plugins]]
repo = 'delphinus/skkeleton_indicator.nvim'
lua_add = '''
    vim.api.nvim_create_autocmd("User", {
      pattern = "DenopsPluginPost:skkeleton",
      callback = function()
        require("skkeleton_indicator").setup()
      end,
    })
'''

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
if = 0
repo = '~/plugin/skk-learning.nvim'
