[[plugins]]
repo = '~/plugin/scorpeon.vim'
depends = 'denops.vim'
on_event = 'BufRead'
hook_add = '''
    let g:scorpeon_extensions_path = [
          \ expand('$CACHE/scorpeon'),
          \ expand('$CACHE/vscode/extensions'),
          \]
    let g:scorpeon_highlight = #{
          \ enable: ['typescript', 'nim'],
          \ disable: { -> getfsize(expand('%')) > 10 * 1024 * 1024 }
          \}
'''

[[plugins]]
repo = 'microsoft/vscode'
if = 0
merged = 0
type__depth = 1
path = '$CACHE/vscode'

[[plugins]]
repo = 'saem/vscode-nim'
if = 0
merged = 0
type__depth = 1
path = '$CACHE/scorpeon/nim'

[[plugins]]
repo = 'oovm/vscode-toml'
if = 0
merged = 0
type__depth = 1
path = '$CACHE/scorpeon/toml'

[[plugins]]
repo = 'emilast/vscode-logfile-highlighter'
if = 0
merged = 0
type__depth = 1
path = '$CACHE/scorpeon/log'
