[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
inoremap <silent><expr> <C-Space> coc#refresh()
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm()
	\ : "\<C-g>u\<CR>\<C-r>=coc#on_enter()\<CR>"
nmap <silent> [d <Plug>(coc-diagnostic-prev)
nmap <silent> ]d <Plug>(coc-diagnostic-next)
nmap <silent> <leader>n <Plug>(coc-rename)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gr <Plug>(coc-references)
augroup format
    au!
    au! BufWritePre * call CocActionAsync('format')
augroup END
nnoremap <silent> K <Cmd>call ShowDocumentation()<CR>
function! ShowDocumentation() abort
	if CocAction('hasProvider', 'hover')
		" call CocActionAsync('doHover')
		call CocAction('doHover')
	else
		call feedkeys('K', 'in')
	endif
endfunction
'''
