[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
function! s:dein_update() abort
    if exists('g:dein#install_github_api_token')
        call dein#check_update(v:true)
    else
        call dein#update()
    endif
endfunction
command DeinUpdate call s:dein_update()
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'milisims/nvim-luaref'

[[plugins]]
repo = 'nanotee/luv-vimdocs'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
