[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
" nnoremap <silent> <leader>f <Cmd>Ddu file_rec<CR>
" nnoremap <silent> <leader>o <Cmd>Ddu file_old<CR>
" nnoremap <silent> <leader>b <Cmd>Ddu buffer<CR>
" " help
" nnoremap <silent> <leader>h <Cmd>Ddu help -ui-param-startFilter<CR>
" " search
" nnoremap <silent> <leader>/ <Cmd>Ddu line -ui-param-startFilter<CR>
" nnoremap <silent> * <Cmd>Ddu line -input=`expand('<cword>')` -ui-param-startFilter=v:false<CR>
" " resume
" nnoremap <silent> <leader>r <Cmd>Ddu -resume -ui-param-startFilter=v:false<CR>
'''
hook_source = '''
call ddu#custom#patch_global({
\       'ui': 'ff',
\       'uiParams': {
\           'ff': {
\               'split': 'floating'
\           },
\       },
\       'sourceOptions': {
\           '_': {
\               'matchers': ['matcher_fzf'],
\               'ignoreCase': v:true,
\           },
\           'dein': {
\               'defaultAction': 'cd',
\           },
\       },
\       'sourceParams': {
\           'file_external': {
\               'cmd': ['git', 'ls-files', '-co', '--exclude-standard'],
\           },
\       },
\       'kindOptions': {
\           'file': {
\               'defaultAction': 'open',
\           },
\           'help': {
\               'defaultAction': 'open'
\           },
\           'word': {
\               'defaultAction': 'append',
\           },
\           'action': {
\               'defaultAction': 'do',
\           },
\       },
\   })
'''

[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent><nowait> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer><silent> <C-l> <Cmd>call ddu#ui#ff#do_action('refreshItems')<CR>
nnoremap <buffer><silent> p <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> a <Cmd>call ddu#ui#ff#do_action('chooseAction')<CR>
nnoremap <buffer><silent> c <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'cd'})<CR>
nnoremap <buffer><silent> d <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'delete'})<CR>
nnoremap <buffer><silent> e <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'edit'})<CR>
nnoremap <buffer><silent> v <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> N <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'new'})<CR>
nnoremap <buffer><silent> r <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'quickfix'})<CR>
nnoremap <buffer><silent> u <Cmd>call ddu#ui#ff#do_action('updateOptions', {'sourceOptions': {'_': {'matchers': []}}})<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
nnoremap <buffer><silent> <CR> <Cmd>close<CR>
" disable nvim-cmp
lua require("cmp").setup.buffer({enabled = false})
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'gamoutatsumi/ddu-source-nvim-lsp'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
on_source = 'ddu.vim'
