[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'ibhagwan/fzf-lua'
depends = 'nvim-web-devicons'
on_cmd = 'FzfLua'
hook_add = '''
nnoremap <F1> <Cmd>FzfLua builtin<CR>
nnoremap <leader>r <Cmd>FzfLua resume<CR>
nnoremap <leader>f <Cmd>FzfLua files<CR>
nnoremap <leader>b <Cmd>FzfLua buffers<CR>
nnoremap <leader>o <Cmd>FzfLua oldfiles<CR>
nnoremap <leader>gr <Cmd>FzfLua live_grep<CR>
nnoremap <leader>/ <Cmd>FzfLua blines<CR>
nnoremap <leader>gf <Cmd>FzfLua git_files<CR>
nnoremap q: <Cmd>FzfLua command_history<CR>
nnoremap q/ <Cmd>FzfLua search_history<CR>

nnoremap <leader>i <Cmd>FzfLua lsp_document_diagnostics<CR>
nnoremap <leader>I <Cmd>FzfLua lsp_workspace_diagnostics<CR>
nnoremap <leader>a <Cmd>FzfLua lsp_code_actions<CR>
nnoremap gd <Cmd>lua require("fzf-lua").lsp_definitions({jump_to_single_result = true})<CR>
nnoremap gr <Cmd>FzfLua lsp_references<CR>
'''
hook_source = '''
lua <<EOL
local fzf = require("fzf-lua")
local actions = require("fzf-lua.actions")

fzf.setup({
    keymap = {
        builtin = {
            ["<C-f>"] = "preview-page-down",
            ["<C-b>"] = "preview-page-up",
        },
        fzf = {
            ["ctrl-f"] = "preview-page-down",
            ["ctrl-b"] = "preview-page-up",
        },
    },
    file_icon_padding = " ",
    files = {
        actions = {
            ["ctrl-x"] = actions.file_split,
        },
    },
    git = {
        actions = {
            ["ctrl-x"] = actions.file_split,
        },
    },
})
EOL
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

[[plugins]]
repo = 'David-Kunz/treesitter-unit'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
depends = ['nvim-treesitter-textobjects', 'nvim-ts-rainbow', 'treesitter-unit']
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOL
require("nvim-treesitter.configs").setup({
    ensure_installed = "all",
    highlight = {
        enable = true,
    },
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["ib"] = "@block.inner",
                ["ab"] = "@block.outer",
                ["c"] = "@comment.outer",
                ["if"] = "@function.inner",
                ["af"] = "@function.outer",
                ["il"] = "@loop.inner",
                ["al"] = "@loop.outer",
            },
        },
        swap = {
            enable = true,
            swap_next = {
                ["<M-s>"] = "@parameter.inner",
            },
            swap_previous = {
                ["<M-S-s>"] = "@parameter.inner",
            },
        },
    },
    rainbow = {
        enable = true,
        extend_mode = true,
        max_file_lines = nil,
    },
})
EOL

xmap iu :lua require("treesitter-unit").select()<CR> 
xmap au :lua require("treesitter-unit").select(true)<CR> 
omap iu <Cmd>lua require("treesitter-unit").select()<CR>
omap au <Cmd>lua require("treesitter-unit").select(true)<CR>
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
depends = 'nvim-treesitter'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

# [[plugins]]
# repo = 'lewis6991/gitsigns.nvim'
# depends = 'nvim-lua/plenary.nvim'
# on_event = 'BufRead'
# hook_source = '''
# lua <<EOL
# local 
# require("gitsigns").setup({
#     on_attach = function(bufnr)
#         local gs = package.loaded.gitsigns

#         local function map(modes, lhs, rhs, opts)
#             opts = opts or {}
#             opts.buffer = bufnr
#             vim.keymap.set(modes, lhs, rhs, opts)
#         end

#         -- Navigation
#         map("n", "]g", "&diff ? ']c' : '<Cmd>Gitsigns next_hunk()<CR>'", { expr = true })
#         map("n", "[g", "&diff ? '[c' : '<Cmd>Gitsigns prev_hunk()<CR>'", { expr = true })

#         -- Actions
#         map("n", "<leader>gp", gs.preview_hunk)

#         -- Text object
#         map({"o", "x"}, "ih", ":<C-u>Gitsigns select_hunk()<CR>")
#     end
# })
# EOL
# '''

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
hook_add = '''
nmap <leader>g <Plug>(Gina)
nmap <silent> <Plug>(Gina)s <Cmd>Gina status -s<CR>
nmap <silent> <Plug>(Gina)c <Cmd>Gina compare<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vim-quickrun-neovim-job'
on_cmd = 'QuickRun'
hook_add = '''
let g:quickrun_config = {
\       '_': {
\           'runner': 'neovim_job',
\           'outputter': 'error',
\           'outputter/error/success': 'buffer',
\           'outputter/error/error': 'quickfix',
\           'outputter/buffer/opener': 'botright 10sp',
\           'outputter/buffer/close_on_empty': v:true,
\       },
\       'lua': {
\           'command': ':luafile',
\           'exec': '%C %S',
\           'runner': 'vimscript',
\       }
\   }

nnoremap @r <Cmd>QuickRun<CR>
augroup quickrun_quit
    au!
    au BufEnter quickrun://output nnoremap <buffer><nowait> q <Cmd>q<CR>
augroup END
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
on_map = { n = [ 'ys', 'yss', 'yS', 'ds', 'dss', 'cs', 'css' ], x = [ 'S' ] }
hook_source = '''
runtime macros/sandwich/keymap/surround.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_source = '''
let g:lexima_ctrlh_as_backspace = 1
call lexima#add_rule({'char': '<CR>', 'at': '\\\s.*\%#$', 'input': '<CR><Bslash> ', 'filetype': 'vim'})
call lexima#add_rule({'char': '<CR>', 'at': '{\%#$}', 'input': '<CR><Bslash> ', 'input_after': '<CR><Bslash> ', 'filetype': 'vim'})
call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'markdown'})
call lexima#add_rule({'char': '$', 'at': '\%#$', 'leave': 1, 'filetype': 'markdown'})
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = { nx = '<Plug>(EasyAlign)' }
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = { n = '<Plug>(operator-replace)' }
hook_add = '''
nmap r <Plug>(operator-replace)
'''

[[plugins]]
repo = 'hrsh7th/vim-eft'
on_map = { nxo = '<Plug>(eft-' }
hook_add = '''
nmap ; <Plug>(eft-repeat)
xmap ; <Plug>(eft-repeat)
nmap f <Plug>(eft-f)
xmap f <Plug>(eft-f)
omap f <Plug>(eft-f)
nmap F <Plug>(eft-F)
xmap F <Plug>(eft-F)
omap F <Plug>(eft-F)
nmap t <Plug>(eft-t)
xmap t <Plug>(eft-t)
omap t <Plug>(eft-t)
nmap T <Plug>(eft-T)
xmap T <Plug>(eft-T)
omap T <Plug>(eft-T)
'''

[[plugins]]
repo = 'hrsh7th/vim-searchx'
on_func = 'searchx#'
hook_add = '''
nnoremap /     <Cmd>call searchx#start({'dir': 1})<CR>
xnoremap /     <Cmd>call searchx#start({'dir': 1})<CR>
nnoremap ?     <Cmd>call searchx#start({'dir': 0})<CR>
xnoremap ?     <Cmd>call searchx#start({'dir': 0})<CR>
nnoremap n     <Cmd>call searchx#next()<CR>
xnoremap n     <Cmd>call searchx#next()<CR>
cnoremap <C-j> <Cmd>call searchx#next()<CR>
nnoremap N     <Cmd>call searchx#prev()<CR>
xnoremap N     <Cmd>call searchx#prev()<CR>
cnoremap <C-k> <Cmd>call searchx#prev()<CR>
nnoremap <C-l> <Cmd>call searchx#clear()<CR>
cnoremap <C-l> <Cmd>call searchx#clear()<CR>
'''
hook_source = '''
let g:searchx = {}
let g:searchx.auto_accept = v:true
let g:searchx.scrolloff = &scrolloff
let g:searchx.scrolltime = 0
let g:searchx.nohlsearch = {}
let g:searchx.nohlsearch.jump = v:true
let g:searchx.markers = split('ASDFGHJKL:QWERTYUIOP', '.\zs')
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-smart-search)'
hook_add = '''
nmap <M-o> <Plug>(openbrowser-smart-search)
xmap <M-o> <Plug>(openbrowser-smart-search)
'''
hook_source = '''
let g:openbrowser_browser_commands = [
\       {'name': 'chrome.exe', 'args': ['{browser}', '{uri}']}
\   ]
'''

[[plugins]]
repo = '~/plugin/translate.nvim'
on_event = 'BufRead'
hook_add = '''
nnoremap ,jf :<C-u>Translate JA -output=floating<CR>
xnoremap ,jf :Translate JA -output=floating<CR>
nnoremap ,js :<C-u>Translate JA -output=split<CR>
xnoremap ,js :Translate JA -output=split<CR>
nnoremap ,ji :<C-u>Translate JA -output=insert<CR>
xnoremap ,ji :Translate JA -output=insert<CR>
nnoremap ,jr :<C-u>Translate JA -output=replace<CR>
xnoremap ,jr :Translate JA -output=replace<CR>

nnoremap ,ef :<C-u>Translate EN -output=floating<CR>
xnoremap ,ef :Translate EN -output=floating<CR>
nnoremap ,es :<C-u>Translate EN -output=split<CR>
xnoremap ,es :Translate EN -output=split<CR>
nnoremap ,ei :<C-u>Translate EN -output=insert<CR>
xnoremap ,ei :Translate EN -output=insert<CR>
nnoremap ,er :<C-u>Translate EN -output=replace<CR>
xnoremap ,er :Translate EN -output=replace<CR>
'''
hook_source = '''
lua <<EOL
require("translate").setup({
    default = {
        command = "deepl_pro",
        output = "floating",
    },
    preset = {
        output = {
            split = {
                append = true,
            },
        },
    },
})
EOL
'''

[plugins.ftplugin]
translate = '''
nnoremap <buffer><nowait> q <Cmd>quit<CR>
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'cd app && yarn install'
on_ft = 'markdown'
hook_source = '''
let g:mkdp_refresh_slow = 1
nnoremap <leader>p <Cmd>MarkdownPreview<CR>
'''

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'
