[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

[[plugins]]
repo = 'David-Kunz/treesitter-unit'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
depends = ['nvim-treesitter-textobjects', 'nvim-ts-rainbow', 'treesitter-unit']
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOL
local map = utils.map

require("nvim-treesitter.configs").setup({
    ensure_installed = "all",
    highlight = {
        enable = true,
    },
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["ib"] = "@block.inner",
                ["ab"] = "@block.outer",
                ["c"] = "@comment.outer",
                ["if"] = "@function.inner",
                ["af"] = "@function.outer",
                ["il"] = "@loop.inner",
                ["al"] = "@loop.outer",
            },
        },
        swap = {
            enable = true,
            swap_next = {
                ["<M-s>"] = "@parameter.inner",
            },
            swap_previous = {
                ["<M-S-s>"] = "@parameter.inner",
            },
        },
    },
    rainbow = {
        enable = true,
        extend_mode = true,
        max_file_lines = nil,
    },
})
EOL

xmap iu :lua require("treesitter-unit").select()<CR> 
xmap au :lua require("treesitter-unit").select(true)<CR> 
omap iu <cmd>lua require("treesitter-unit").select()<CR>
omap au <cmd>lua require("treesitter-unit").select(true)<CR>

" let s:operators = ['c', 'd', 'y', '=', '<', '>']
" for operator in s:operators
"     exec 'nnoremap ' . operator . ' <cmd>lua require("treesitter-unit").enable_highlighting()<CR>' . operator
" endfor
" 
" augroup tsunit
"     au !
"     au CursorMoved * lua require('treesitter-unit').disable_highlighting()
" augroup END
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
depends = 'nvim-treesitter'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'BufRead'
hook_source = '''
lua <<EOL
require("gitsigns").setup({
    keymaps = {
        noremap = true,

        ["n ]g"] = {
            expr = true,
            "&diff ? ']c' : '<cmd>lua require\"gitsigns.actions\".next_hunk()<CR>'",
        },
        ["n [g"] = {
            expr = true,
            "&diff ? '[c' : '<cmd>lua require\"gitsigns.actions\".prev_hunk()<CR>'",
        },

        ["n <leader>gp"] = '<cmd>lua require"gitsigns".preview_hunk()<CR>',

        -- Text objects
        ["o ih"] = ':<C-U>lua require"gitsigns.actions".select_hunk()<CR>',
        ["x ih"] = ':<C-U>lua require"gitsigns.actions".select_hunk()<CR>',
    },
})
EOL
'''

[[plugins]]
repo = 'feline-nvim/feline.nvim'
depends = 'nvim-web-devicons'
on_event = 'VimEnter'
hook_source = '''
lua <<EOL
local f = vim.fn

local theme = {
    bg = "#1d3b53",
    dark_blue = "#092236",
    cadet_blue = "#a1aab8",
    white_blue = "#d6deeb",
    yellow = "#e3d18a",
    peach = "#ffcb8b",
    tan = "#ecc48d",
    orange = "#f78c6c",
    red = "#fc514e",
    watermelon = "#ff5874",
    violet = "#c792ea",
    purple = "#ae81ff",
    indigo = "#5e97ec",
    blue = "#82aaff",
    turquoise = "#7fdbca",
    emerald = "#21c7a8",
    green = "#a1cd5e",
}

local vi_mode_colors = {
    NORMAL = "indigo",
    OP = "indigo",
    INSERT = "white_blue",
    VISUAL = "purple",
    BLOCK = "purple",
    REPLACE = "watermelon",
    ["V-REPLACE"] = "watermelon",
    ENTER = "yellow",
    MORE = "yellow",
    SELECT = "watermelon",
    COMMAND = "emerald",
    SHELL = "emerald",
    TERM = "emerald",
    NONE = "yellow",
}

local icons = {
    diagnostic = {
        error = "  ",
        warn = "  ",
        hint = "  ",
        info = "  ",
    },
    diff = {
        added = " ",
        changed = " ",
        removed = " ",
    },
}

local vi_mode = require("feline.providers.vi_mode")
local git = require("feline.providers.git")
local devicons = require("nvim-web-devicons")

local comps = {
    vi_mode = {
        provider = function()
            local mode = vi_mode.get_vim_mode()
            return "  " .. mode .. " "
        end,
        hl = function()
            return {
                fg = "dark_blue",
                bg = vi_mode.get_mode_color(),
            }
        end,
        right_sep = " ",
    },
    file = {
        name = {
            provider = function()
                return f.expand("%:t")
            end,
            hl = {
                fg = "purple",
                style = "bold",
            },
        },
        icon = {
            provider = function()
                local icon, _ = devicons.get_icon(f.expand("%:t"))
                return icon or ""
            end,
            hl = function()
                local _, cc = devicons.get_icon_color(f.expand("%:t"))
                return {
                    fg = cc,
                }
            end,
            right_sep = " ",
        },
        fullpath = {
            provider = function()
                return f.expand("%:p")
            end,
            hl = {
                fg = "emerald",
            },
        },
    },
    lsp = {
        servers = {
            provider = "lsp_client_names",
            icon = "  ",
            hl = {
                fg = "emerald",
            },
        },
        error = {
            provider = "diagnostic_errors",
            icon = icons.diagnostic.error,
            hl = {
                fg = "red",
            },
        },
        warn = {
            provider = "diagnostic_warnings",
            icon = icons.diagnostic.warn,
            hl = {
                fg = "yellow",
            },
        },
        hint = {
            provider = "diagnostic_hints",
            icon = icons.diagnostic.hint,
            hl = {
                fg = "white_blue",
            },
        },
        info = {
            provider = "diagnostic_info",
            icon = icons.diagnostic.info,
            hl = {
                fg = "blue",
            },
        },
    },
    git = {
        branch = {
            provider = function()
                local head, icon = git.git_branch(0)
                return icon .. head
            end,
            enabled = function()
                return git.git_branch(0) ~= ""
            end,
            hl = {
                fg = "purple",
            },
        },
        diff = {
            add = {
                provider = function()
                    return git.git_diff_added(0)
                end,
                icon = icons.diff.added,
                enabled = function()
                    return git.git_diff_added(0) ~= ""
                end,
                hl = {
                    fg = "green",
                },
                left_sep = " ",
            },
            change = {
                provider = function()
                    return git.git_diff_changed(0)
                end,
                icon = icons.diff.changed,
                enabled = function()
                    return git.git_diff_changed(0) ~= ""
                end,
                hl = {
                    fg = "yellow",
                },
                left_sep = " ",
            },
            remove = {
                provider = function()
                    return git.git_diff_removed(0)
                end,
                icon = icons.diff.removed,
                enabled = function()
                    return git.git_diff_removed(0) ~= ""
                end,
                hl = {
                    fg = "red",
                },
                left_sep = " ",
            },
        },
    },
    cursor = {
        pos_per = {
            provider = function()
                local c = require("feline.providers.cursor")
                return " " .. c.position(nil, {}) .. " " .. c.line_percentage() .. " "
            end,
            hl = {
                fg = "bg",
                bg = "emerald",
            },
            left_sep = " ",
        },
        bar = {
            provider = "scroll_bar",
            hl = {
                fg = "emerald",
            },
        },
    },
}

local components = {
    active = { {}, {}, {} },
    inactive = { {}, {}, {} },
}

function components.active_add(self, n, x)
    table.insert(self.active[n], x)
end

function components.inactive_add(self, n, x)
    table.insert(self.inactive[n], x)
end

components:active_add(1, comps.vi_mode)
components:active_add(1, comps.file.icon)
components:active_add(1, comps.file.name)
components:active_add(1, comps.lsp.error)
components:active_add(1, comps.lsp.warn)
components:active_add(1, comps.lsp.hint)
components:active_add(1, comps.lsp.info)
components:active_add(2, comps.git.branch)
components:active_add(2, comps.git.diff.add)
components:active_add(2, comps.git.diff.change)
components:active_add(2, comps.git.diff.remove)
components:active_add(3, comps.lsp.servers)
components:active_add(3, comps.cursor.pos_per)
components:active_add(3, comps.cursor.bar)
components:inactive_add(1, comps.file.fullpath)

require("feline").setup({
    vi_mode_colors = vi_mode_colors,
    components = components,
    force_inactive = {
        filetypes = {
            "filittle",
            "quickrun",
        },
    },
})

require("feline").use_theme(theme)
EOL
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'cd app && yarn install'
on_ft = 'markdown'
hook_source = '''
let g:mkdp_refresh_slow = 1
nnoremap <leader>p <cmd>MarkdownPreview<CR>
'''
