[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'tami5/lspsaga.nvim'

[[plugins]]
repo = 'folke/lua-dev.nvim'

[[plugins]]
repo = 'j-hui/fidget.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'lspsaga.nvim', 'lua-dev.nvim', 'fidget.nvim', 'cmp-nvim-lsp']
on_ft = ['lua', 'go', 'python', 'bash', 'rust', 'vim', 'typescript']
hook_source = '''
command Format lua vim.lsp.buf.formatting_sync()

augroup lspinfo_close
    au!
    au FileType lspinfo nnoremap <buffer><nowait> q <Cmd>q<CR>
augroup END

function! Lspmapping() abort
    nnoremap <buffer> K         <Cmd>Lspsaga hover_doc<CR>
    nnoremap <buffer> [d        <Cmd>Lspsaga diagnostic_jump_prev<CR>
    nnoremap <buffer> ]d        <Cmd>Lspsaga diagnostic_jump_next<CR>
    nnoremap <buffer> <leader>n <Cmd>Lspsaga rename<CR>
    nnoremap <buffer> <leader>x <Cmd>Lspsaga code_action<CR>
    xnoremap <buffer> <leader>x <Cmd>Lspsaga range_code_action<CR>
    nnoremap <buffer> <C-f>     <Cmd>lua require("lspsaga.action").smart_scroll_with_saga(1)<CR>
    nnoremap <buffer> <C-b>     <Cmd>lua require("lspsaga.action").smart_scroll_with_saga(-1)<CR>
endfunction

lua <<EOL
local lspinstaller = require("nvim-lsp-installer")

-- cmp source
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require("cmp_nvim_lsp").update_capabilities(capabilities)

-- lsp saga
require("lspsaga").setup({
    error_sign = " ",
    warn_sign = " ",
    hint_sign = " ",
    infor_sign = " ",
    code_action_prompt = {
        enable = false,
    },
    code_action_keys = {
        quit = { "<C-c>", "<Esc>", "q" },
        exec = "<CR>",
    },
    rename_action_keys = {
        quit = { "<C-c>", "<Esc>" },
        exec = "<CR>",
    },
})

-- LSP setting
local opts = {
    default = {
        capabilities = capabilities,
        on_attach = function()
            vim.fn["Lspmapping"]()
        end,
    },
}

opts.sumneko_lua = require("lua-dev").setup({
    library = {
        vimruntime = true,
        types = true,
        plugins = { "plenary.nvim", "LuaSnip" },
    },
    lspconfig = opts.default,
})
-- disable completion snippet
opts.sumneko_lua.settings.Lua.completion = nil

-- setup
lspinstaller.on_server_ready(function(server)
    local opt = opts[server.name] or opts.default
    server:setup(opt)
    vim.cmd([[do User LspAttachBuffers]])
end)

local command = vim.api.nvim_create_user_command

-- setup command
command("LspSetup", function()
    local servers = {
        "sumneko_lua",
        "gopls",
        "pyright",
        "bashls",
        "rust_analyzer",
        "vimls",
        "denols",
    }
    for _, server in ipairs(servers) do
        lspinstaller.install(server)
    end
end, {})
EOL
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
on_ft = ['lua', 'sh', 'json', 'python', 'teal']
hook_source = '''
lua <<EOL
local null = require("null-ls")
local b = null.builtins

null.setup({
    sources = {
        function()
            local utils = require("null-ls.utils").make_conditional_utils()
            if utils.root_has_file("stylua.toml") then
                return b.formatting.stylua
            elseif utils.root_has_file(".stylua.toml") then
                return b.formatting.stylua.with({
                    extra_args = { "--config-path", "./.stylua.toml" },
                })
            else
                return b.formatting.stylua.with({
                    extra_args = { "--config-path", vim.fn.expand("~/.config/stylua.toml") },
                })
            end
        end,
        b.formatting.shfmt.with({
            extra_args = { "-ci", "-s", "-bn", "-i", "4" },
        }),
        b.formatting.fixjson,
        b.formatting.black,
        b.diagnostics.shellcheck.with({ diagnostics_format = "#{m} [#{c}]" }),
        b.diagnostics.teal,
    },
})
EOL
'''
