[[plugins]]
repo = 'tami5/lspsaga.nvim'
hook_source = '''
lua <<EOL
require("lspsaga").setup({
    error_sign = " ",
    warn_sign = " ",
    hint_sign = " ",
    infor_sign = " ",
    code_action_prompt = {
        enable = false,
    },
    code_action_keys = {
        quit = { "<C-c>", "<Esc>", "q" },
        exec = "<CR>",
    },
    rename_action_keys = {
        quit = { "<C-c>", "<Esc>" },
        exec = "<CR>",
    },
})
EOL
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
hook_source = '''
lua require("fidget").setup({})
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'junnplus/nvim-lsp-setup'

[[plugins]]
# repo = 'folke/lua-dev.nvim'
repo = '~/plugin/lua-dev.nvim'

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = 'denops.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['lspsaga.nvim', 'fidget.nvim', 'nvim-lsp-installer', 'nvim-lsp-setup', 'lua-dev.nvim', 'denops-signature_help', 'cmp-nvim-lsp']
on_ft = ['lua', 'go', 'python', 'sh', 'bash', 'rust', 'vim', 'typescript']
hook_source = '''
command Format lua vim.lsp.buf.formatting_sync()

augroup lspinfo_close
    au!
    au FileType lspinfo nnoremap <buffer><nowait> q <Cmd>q<CR>
augroup END

lua <<EOL
require("nvim-lsp-setup").setup({
    installer = {
        ensure_installed = {
            "sumneko_lua",
            "gopls",
            "pyright",
            "bashls",
            "rust_analyzer",
            "vimls",
            "denols",
        },
        automatic_installation = true,
    },
    default_mappings = false,
    mappings = {
        K = "Lspsaga hover_doc",
        ["[d"] = "Lspsaga diagnostic_jump_prev",
        ["]d"] = "Lspsaga diagnostic_jump_next",
        ["<leader>n"] = "Lspsaga rename",
        ["<leader>x"] = "Lspsaga code_action",
        ["<leader>x"] = "Lspsaga range_code_action",
        ["<C-f>"] = "lua require('lspsaga.action').smart_scroll_with_saga(1)",
        ["<C-b>"] = "lua require('lspsaga.action').smart_scroll_with_saga(-1)",
    },
    capabilities = capabilities,
    on_attach = function(client, bufnr)
        require('nvim-lsp-setup.utils').format_on_save(client)
        vim.keymap.set("i", "<C-g>", function()
            if vim.fn["signature_help#is_enabled"]() == 1 then
                print("disable")
                vim.fn["signature_help#disable"]()
            else
                print("enable")
                vim.fn["signature_help#enable"]()
            end
        end, { buffer = true })
    end,
    servers = {
        sumneko_lua = require("lua-dev").setup({
            library = {
                vimruntime = true,
                types = true,
                plugins = { "plenary.nvim", "LuaSnip" },
            },
            snippet = false,
        }),
		gopls = {},
        pyright = {},
		bashls = {},
		rust_analyzer = {},
		vimls = {},
		denols = {},
    },
})
EOL
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = 'plenary.nvim'
on_ft = ['lua', 'sh', 'json', 'python', 'teal']
hook_source = '''
lua <<EOL
local null = require("null-ls")
local b = null.builtins

null.setup({
    sources = {
        function()
            local utils = require("null-ls.utils").make_conditional_utils()
            if utils.root_has_file("stylua.toml") then
                return b.formatting.stylua
            elseif utils.root_has_file(".stylua.toml") then
                return b.formatting.stylua.with({
                    extra_args = { "--config-path", "./.stylua.toml" },
                })
            else
                return b.formatting.stylua.with({
                    extra_args = { "--config-path", vim.fn.expand("~/.config/stylua.toml") },
                })
            end
        end,
        b.formatting.shfmt.with({
            extra_args = { "-ci", "-s", "-bn", "-i", "4" },
        }),
        b.formatting.fixjson,
        b.formatting.black,
        b.diagnostics.shellcheck.with({ diagnostics_format = "#{m} [#{c}]" }),
        b.diagnostics.teal,
    },
})
EOL
'''
